### ISSUE TITLE
math font with serif

### ISSUE THREAD

**Issue by psteinb** [Helmholtz-AI-Energy/beamer-template-2024#5]
the default in this beamer theme is again a math font sans-serif. This is sometimes hard to read. How would one enable a math font with serifs again? The old theme was capable of doing so.

**Comment by Markus-Goetz** [comment]
From the old slides deck

```
% Use standard TeX math font.
%
% Copy or link /path/to/beamerfontthemeserif.sty into theme/, e.g.
%   cd theme
%   ln -s /usr/share/texlive/texmf-dist/tex/latex/beamer/beamerfontthemeserif.sty beamerfontthemeserif.sty
%%\usepackage{lmodern}
%%\usefonttheme[onlymath]{serif}
```

Should this maybe be reintroduced into the slides.tex file?

**Comment by psteinb** [comment]
I think that is enough. I am sending a PR.
